### ISSUE TITLE
Broken links for the viewer configuration sub-tpics

### ISSUE THREAD

**Issue by jweyl11** [cmv/cmv-docs#12]
Hi -
When I go to the documentation, I am not able to click on the sub categories to work on each sub-category.
http://docs.cmv.io/en/1.3.4/configure/viewer/

then click on http://docs.cmv.io/en/1.3.4/configure/configure/esriConfig 
and I get back Maze- You have found something that doesn't exist. 

This happens on each link.

Thanks,
Joe

**Comment by tmcgee** [comment]
Hmm. Thanks for pointing that out. The links work for the [1.3.3 version of the docs](http://docs.cmv.io/en/1.3.3/configure/viewer). I suspect that the links broke because of updated code in readthedocs between the cmv releases. We'll address that in the next release.

**Comment by green3g** [comment]
This should be fixed with https://github.com/cmv/cmv-docs/pull/15
