### ISSUE TITLE
Find Widget Documentation

### ISSUE THREAD

**Issue by knozaki2001** [cmv/cmv-docs#3]
I think there is an error on the find documentation (http://docs.cmv.io/en/1.3.3/widgets/Find/). It has an example for editor instead.

**Comment by tmcgee** [comment]
@jebu consider this when you update the docs for the Find widget.

**Comment by jebu75** [comment]
@tmcgee, thanks and sorry for not getting to that sooner.  I think you pointed that out some time ago as well.

**Comment by tmcgee** [comment]
new Find documentation will be in 1.3.4 release
