### ISSUE TITLE
Wrong links to gis.stackexchange.com

### ISSUE THREAD

**Issue by gf59ru** [cmv/cmv-docs#6]
You have wrong links to gis.stackexchange.com, namely tag
`https://gis.stackexchange.com/tag/cmv` proceeds to 404 page
And I found `https://gis.stackexchange.com/questions/tagged/configurable-map-viewer` in gis.stackexchange.com tags

Wrong links was found in `support.md` and `contribute/index.md`

**Comment by tmcgee** [comment]
@gf59ru Good catch! The URLs in the docs are just missing an `s`. It should be `tags` not `tag`. CMV is a synonym for Configurable Map Viewer at stackexchange so either one works. We prefer cmv but stackexchange requires the tag be more descriptive. This will be fixed in the next release.

**Comment by tmcgee** [comment]
Fixed the link in `contribute/index.md` in #10. The link in `support.md` is fine.
